config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#forbidden_error', via: :all

  devise_for :administrators

  root 'events#index'
  resources :organizers
  resources :subscribers, only: :create
  resources :events do
    get 'search', on: :collection
  end

  namespace :admin do
    resource :dashboard, only: :index
    root to: 'dashboard#index'
    resources :organizers, :events, :tags
    resources :subscribers, except: :show
  end
end

app/models/organizer.rb
# frozen_string_literal: true

class Organizer < ApplicationRecord
  has_many :events, dependent: :destroy
  validates :name, uniqueness: { case_sensitive: false, message: ' должено быть уникальным' },
                   presence: { message: 'не может быть пустым' }
  validates :description, length: { maximum: 255, message: 'максимальное число символов 255' }
end

app/controllers/admin/organizers_controller.rb
# frozen_string_literal: true

module Admin
  class OrganizersController < AdminController
    def index
      @organizers = Organizer.paginate(page: params[:page], per_page: 9)
    end

    def show
      @organizer = Organizer.find(params[:id])
    end

    def new
      @organizer = Organizer.new
    end

    def edit
      @organizer = Organizer.find(params[:id])
    end

    def create
      @organizer = Organizer.new(organizer_params)
      if @organizer.save
        flash[:success] = 'Организатор успешно создан'
        redirect_to [:admin, @organizer]
      else
        flash[:danger] = 'Во время создания произошла ошибка'
        render 'new'
      end
    end

    def update
      @organizer = Organizer.find(params[:id])
      if @organizer.update(organizer_params)
        flash[:success] = 'Организатор успешно изменён'
        redirect_to [:admin, @organizer]
      else
        flash[:danger] = 'Во время редактирования произошла ошибка'
        render 'edit'
      end
    end

    def destroy
      @organizer = Organizer.find(params[:id])
      flash[:success] = if @organizer.destroy
                          'Организатор успешно удалён'
                        else
                          'Во время удаления произошла ошибка'
                        end
      redirect_to admin_organizers_path
    end

    private

    def organizer_params
      params.require(:organizer).permit(:name, :description)
    end
  end
end

app/controllers/organizers_controller.rb
# frozen_string_literal: true

class OrganizersController < ApplicationController
  def index
    @organizers = Organizer.paginate(page: params[:page], per_page: 8)
  end

  def show
    @organizer = Organizer.includes(:events).find(params[:id])
  end
end

app/helpers/organizers_helper.rb
# frozen_string_literal: true

module OrganizersHelper
end

app/views/admin/organizers/_form.html.erb
<%= form_with( model: [:admin, @organizer], local: true) do |form| %>
  <% if @organizer.errors.any? %>
    <div id="error_explanation">
        <% @organizer.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger" role="alert">
            <%= msg %>
          </div>
        <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <label for="exampleInputEmail1">Имя</label>
    <%= form.text_field :name, placeholder: "Имя", class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Краткое описание</label>
    <%= form.text_field :description, placeholder: "Описание", class: "form-control"%>
  </div>
  <%= form.submit "Сохранить", :class => 'btn btn-primary' %>
  <%= link_to   admin_organizers_path, class: 'btn btn-outline-success mt-2 mb-2' do %>
    Назад к организаторам
  <% end %>
<% end %>

app/views/admin/organizers/edit.html.erb
<div class="row justify-content-center pt-5">
  <div class="col-md-8">
    <div class="card">
      <header class="card-header">
        Редактирование организатора
      </header>
      <div class="card-body">
        <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/organizers/index.html.erb
<section  class="pt-3 pb-2">
  <div class="container">
    <h3 class="">Список организаторов</h3>
    <%= link_to new_admin_organizer_path, class: current_class?(new_organizer_path)+' btn btn-outline-success mt-2 mb-2' do %>
      <i class="fa fa-plus" aria-hidden="true"></i> Добавить организатора
    <% end %>
  </div>
</section>
<div class="container">
      <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
        <thead>
        <tr role="row">
          <th>Наименование</th>
          <th></th></tr>
        </thead>
        <tbody>
      <% @organizers.each do |org| %>
          <tr role="row" class="odd">
            <td><%= link_to  org.name, admin_organizer_path(org) %></td>
            <td>
              <%= link_to edit_admin_organizer_path(org), class: "btn btn-primary btn-sm", title: "Редактировать" do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= link_to admin_organizer_path(org), method: :delete, class: "btn btn-danger btn-sm", title: "Удалить",  data: { confirm: "Вы уверены, что хотите удалить?" } do %>
                <i class="fa fa-trash-o "></i>
              <%end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <nav  class="mt-5 pagination justify-content-center digg_pagination">
          <%= will_paginate @organizers  %>
    </nav>
</div>

app/views/admin/organizers/new.html.erb
<div class="row justify-content-center pt-5">
  <div class="col-md-8">
    <div class="card">
      <header class="card-header">
        Добавление организатора
      </header>
      <div class="card-body">
        <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/organizers/show.html.erb
<div class="row justify-content-center pt-5">
  <div class="col-md-8">
    <div class="card">
      <header class="card-header">
        Просмотр организатора
      </header>
      <div class="card-body">
        <b>Наименование:</b> <span><%= @organizer.name %></span>
        <% unless @organizer.description.blank? %>
        <hr>
          <b>Краткое описание:</b> <span><%= @organizer.description %></span>
        <% end %>
      </div>
    </div>  <%= link_to   admin_organizers_path, class: 'btn btn-outline-success mt-2 mb-2' do %>
      Назад к организаторам
    <% end %>
  </div>
</div>