config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#forbidden_error', via: :all

  devise_for :administrators

  root 'events#index'
  resources :organizers
  resources :subscribers, only: :create
  resources :events do
    get 'search', on: :collection
  end

  namespace :admin do
    resource :dashboard, only: :index
    root to: 'dashboard#index'
    resources :organizers, :events, :tags
    resources :subscribers, except: :show
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :organizer
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags

  scope :city, ->(city) { where('city ILIKE ?', "%#{city}%") if city.present? }
  scope :date_start, ->(date_start) { where('DATE(event_date) = ?', Time.parse(date_start).strftime('%Y/%m/%d')) if date_start.present? }
  scope :past_or_future, ->(filter_date) do
    return unless filter_date.present?
    condition = filter_date == 'last'?  'event_date < ?' : 'event_date > ?'
    where(condition, DateTime.now)
  end
  scope :organizer, ->(organizer) { joins(:organizer).where('organizers.name ILIKE ?', "%#{organizer}%") if organizer.present? }

  validates :city, :location, :image, :organizer, presence: true
  validates :title, length: { minimum: 5, message: 'минимальное число символов 5' }, presence: true
  validates :link,
            format: { with: %r{\Ahttps?://[www]?[a-zA-Z0-9_-]*[.][a-z]{2,}(/.*)?\z},
                      message: 'введите корректный url адрес' }
  validates :event_date, presence: true
  validate :valid_datetime

  # Validate date format
  #
  def valid_datetime
    errors.add(:event_date, 'требуемый формат DD-MM-YYYY hh:mm') unless event_date.methods.include? :strftime
  end

  # Convert to iCalendar
  #
  def to_ics
    event = Icalendar::Event.new
    event.dtstart = event_date.strftime('%Y%m%dT%H%M%S')
    event.summary = title
    event.description = description
    event.location = "#{city} #{location}"
    event.ip_class = 'PUBLIC'
    event.created = created_at
    event.last_modified = updated_at
    event.uid = event.url = "#events/#{id}"
    event
  end

  # Search by title or description
  #
  def self.search(search, page = 1)
    Event.where('title ILIKE ? OR description ILIKE ?', "%#{search}%", "%#{search}%")
         .order('event_date DESC').paginate(page: page, per_page: 8)
  end

  # Find events by event date
  #
  def self.find_by_date(date)
    begin
      date = date.to_date
    rescue StandardError
      date = Time.now + 86_400 # so if we don`t get valid date, set tomorrow
    end

    Event.where('DATE(event_date) = ?', date)
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < AdminController
    def index
      @events = Event.order('event_date DESC').paginate(page: params[:page], per_page: 9)
    end

    def show
      @event = Event.find(params[:id])
    end

    def new
      @event = Event.new
    end

    def edit
      @event = Event.find(params[:id])
      p @event.tags
    end

    def create
      @event = Event.new(event_params)
      if @event.save
        flash[:success] = 'Событие успешно создано'
        redirect_to [:admin, @event]
      else
        flash[:danger] = 'Во время создания произошла ошибка'
        render 'new'
      end
    end

    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        flash[:success] = 'Событие успешно изменено'
        redirect_to [:admin, @event]
      else
        flash[:danger] = 'Во время редактирования произошла ошибка'
        render 'edit'
      end
    end

    def destroy
      @event = Event.find(params[:id])
      flash[:success] = if @event.destroy
                          'Событие успешно удалено'
                        else
                          'Во время удаления произошла ошибка'
                        end
      redirect_to admin_events_path
    end

    private

    def event_params
      params.require(:event).permit(:title, :city, :location, :link, :event_date, :image, :description, :organizer_id, tag_ids: [])
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

require 'icalendar'

class EventsController < ApplicationController
  def index
    @events = ::Events::Filter.run!(params: events_params.to_hash)
    respond_to do |format|
      format.js { render partial: 'filter' }
      format.html { render :index }
    end
  end

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html
      format.ics do
        calendar = Icalendar::Calendar.new
        calendar.add_event(@event.to_ics)
        calendar.publish
        render plain: calendar.to_ical
      end
    end
  end

  def search
    @events = ''
    @events = Event.search(params[:search], params[:page]) if params.key?('search') && !params[:search].empty?
  end

  def events_params
    params_list = [
      :page,
      :filter_date,
      :date_start,
      :city,
      :organizer,
      :reset,
      :submit
    ]
    params.permit(*params_list)
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def formatted_time(date)
    date.strftime('%k:%M')
  end

  def formatted_date(date)
    date.strftime('%d.%m.%Y')
  end
end

app/views/admin/events/_form.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'select2.min.css' %>
  <%= stylesheet_link_tag 'bootstrap-datepicker.min.css' %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/suggestions-jquery@20.3.0/dist/css/suggestions.min.css' %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag "select2.min.js" %>
  <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/suggestions-jquery@20.3.0/dist/js/jquery.suggestions.min.js" %>
  <%= tinymce_assets %>
  <%= javascript_include_tag "moment.min.js" %>
  <%= javascript_include_tag "bootstrap-datetimepicker.min.js" %>
<% end %>

<%= form_with(model:[:admin, @event], local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <% @event.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger" role="alert">
          <%= msg %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <label for="exampleInputEmail1">Название</label>
    <%= form.text_field :title, placeholder: "Название", class: "form-control"%>
  </div>
  <%- #todo:image upload -%>
  <div class="form-group">
    <label for="exampleInputEmail1">Город</label>
    <%= form.text_field :city, placeholder: "Город", class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Место проведения</label>
    <%= form.text_field :location, placeholder: "Место проведения", class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Организатор</label>
    <%= form.collection_select(:organizer_id, Organizer.all, :id, :name, {}, { :class=>'select2 form-control'} ) %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Внешняя ссылка</label>
    <%= form.url_field :link, placeholder: "Внешняя ссылка", class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Дата и время</label>
    <%= form.text_field :event_date, placeholder: "Дата и время", class: "datetime-input form-control"%>
  </div>
  <div class="form-group">
    <label for="exampleFormControlFile1">Изображение</label>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Описание</label>
    <%= form.text_area :description, placeholder: "Описание", class: "tinymce form-control"%>
  </div>
  <div class="form-checkbox">
    <p>Tags:</p>
    <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name, {multiple: true, class: 'checkbox form-check-input inline'}) do |b|%>
      <div class="form-check">
        <%=   b.label(:"data-value" => b.value, class: "form-check-label") { b.check_box(class: "form-check-input") + b.text } %>
      </div>
    <% end %>
  </div>

  <%- #todo: organizer field -%>
  <%= form.submit "Сохранить", :class => 'btn btn-primary' %>
  <%= link_to   admin_events_path, class: 'btn btn-outline-success mt-2 mb-2' do %>
    Назад к событиям
  <% end %>
<% end %>

app/views/admin/events/edit.html.erb
<div class="row justify-content-center pt-5">
  <div class="col-md-8">
    <div class="card">
      <header class="card-header">
        Редактирование события
      </header>
      <div class="card-body">
        <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/events/index.html.erb
<section  class="pt-3 pb-2">
  <div class="container">
    <h3 class="">Список событий</h3>
    <%= link_to new_admin_event_path, class: ' btn btn-outline-success mt-2 mb-2' do %>
      <i class="fa fa-plus" aria-hidden="true"></i> Добавить событие
    <% end %>
  </div>
</section>
<div class="container">
      <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
        <thead>
        <tr role="row">
          <th>Наименование</th>
          <th></th></tr>
        </thead>
        <tbody>
      <% @events.each do |event| %>
          <tr role="row" class="odd">
            <td><%= link_to  event.title, admin_event_path(event) %></td>
            <td>
              <%= link_to edit_admin_event_path(event), class: "btn btn-primary btn-sm", title: "Редактировать" do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= link_to admin_event_path(event), method: :delete, class: "btn btn-danger btn-sm", title: "Удалить",  data: { confirm: "Вы уверены, что хотите удалить?" } do %>
                <i class="fa fa-trash-o "></i>
              <%end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <nav  class="mt-5 pagination justify-content-center digg_pagination">
          <%= will_paginate @events  %>
    </nav>
</div>

app/views/admin/events/new.html.erb
<div class="row justify-content-center pt-5">
  <div class="col-md-8">
    <div class="card">
      <header class="card-header">
        Добавление события
      </header>
      <div class="card-body">
        <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/events/show.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag "https://api-maps.yandex.ru/2.1/?apikey=74e2696c-307e-46f7-9889-91dafb6ed2d4&lang=ru_RU" %>
  <%= javascript_include_tag "maps" %>
<% end %>
<div class="row justify-content-center pt-5">
  <div class="col-md-8">
    <div class="card">
      <header class="card-header">
        Просмотр события
      </header>
      <div class="card-body">
        <% if @event.image? %>
          <div class="col-md-6 ">
            <%= image_tag @event.image.url, class: "img-retina img-fluid" %>
          </div>
          <hr>
        <% end %>
        <b>Наименование:</b> <span><%= @event.title %></span>
        <hr>
        <b>Город:</b> <span id="event_city"><%= @event.city %></span>
        <hr>
        <b>Расположение:</b> <span id="event_location"><%= @event.location %></span>
        <hr>
        <b>Дата:</b> <span><%= formatted_date(@event.event_date) %></span>
        <hr>
        <b>Время:</b> <span> <%= formatted_time(@event.event_date)%></span>
        <hr>
        <b>Организатор:</b> <span> <%= @event.organizer.name %></span>
        <hr>
        <b>Url:</b><span> <%= link_to 'Ссылка на мероприятие',  @event.link %></span>
        <% unless @event.description == nil || @event.description == "" %>
          <hr>
          <div class="event-description pt-5 pb-5">
            <%= @event.description.html_safe  %>
          </div>
        <% end %>
        <hr>
        <% unless @event.tags.empty? %>
          <% @event.tags.each do |tag| %>
          <span class="badge badge-light"><%=tag.name %></span>
          <% end %>
        <% end %>
        <hr>
        <div id="map" style="width: 100%; height: 400px"></div>
      </div>
    </div>
    <%= link_to admin_events_path, class: 'btn btn-outline-success mt-2 mb-2' do %>
      Назад к событиям
    <% end %>
  </div>
</div>