config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#forbidden_error', via: :all

  devise_for :administrators

  root 'events#index'
  resources :organizers
  resources :subscribers, only: :create
  resources :events do
    get 'search', on: :collection
  end

  namespace :admin do
    resource :dashboard, only: :index
    root to: 'dashboard#index'
    resources :organizers, :events, :tags
    resources :subscribers, except: :show
  end
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Admin part | Ruby on Rails test App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= yield(:stylesheets) %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="sb-nav-fixed  ">
  <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <button class="btn btn-link btn-sm order-0 order-lg-0" id="sidebarToggle" href="#">
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button><!-- Navbar Search-->
    <a class="navbar-brand" href="/admin">Админка</a>
    <!-- Navbar-->

  </nav>
  <div id="layoutSidenav">
    <div id="layoutSidenav_nav">
      <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
          <div class="nav">
            <%= link_to admin_events_path, class: current_class?(admin_events_path)+' nav-link  ' do %>
              <i class="fa fa-calendar" aria-hidden="true"></i>
              Мероприятия
            <% end %>
            <%= link_to admin_organizers_path, class: current_class?(admin_organizers_path)+' nav-link  ' do %>
              <i class="fa fa-users" aria-hidden="true"></i>
              Организаторы
            <% end %>
            <%= link_to admin_tags_path, class: current_class?(admin_tags_path)+' nav-link  ' do %>
              <i class="fa fa-tags" aria-hidden="true"></i>
              Теги
            <% end %>
            <%= link_to admin_subscribers_path, class: current_class?(admin_subscribers_path)+' nav-link  ' do %>
              <i class="fa fa-envelope-open-o" aria-hidden="true"></i>
              Подписчики
            <% end %>
            <%= link_to root_path, class: 'nav-link ' do %>
              <i class="fa fa-eye" aria-hidden="true"></i>
              Перейти на сайт
            <% end %>
            <%= link_to destroy_administrator_session_path, method: :delete, class: 'nav-link' do %>
              <i class="fa fa-sign-out" aria-hidden="true"></i> Выйти
            <% end %>
          </div>
        </div>
        <div class="sb-sidenav-footer">
          <div class="small">Logged in as:</div>
          Admin
        </div>
      </nav>
    </div>
    <div id="layoutSidenav_content">
      <main>
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-12">
              <% flash.each do |message_type, message| %>
                <div role="alert" class="mt-4 alert alert-<%= message_type %>"><%= message %></div>
              <% end %>
              <%= yield %>
            </div>
          </div>
         </div>
      </main>
     </div>
  </div>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'false' %>
  <%= javascript_include_tag 'jquery-3.5.1.min' %>
  <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js' %>
  <%= yield(:javascripts) %>
  <%= javascript_include_tag 'admin' %>
  </body>
</html>