config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#forbidden_error', via: :all

  devise_for :administrators

  root 'events#index'
  resources :organizers
  resources :subscribers, only: :create
  resources :events do
    get 'search', on: :collection
  end

  namespace :admin do
    resource :dashboard, only: :index
    root to: 'dashboard#index'
    resources :organizers, :events, :tags
    resources :subscribers, except: :show
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <div id="subscription_area">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="subscribe_now">
              <h4>Хотите быть в курсе последних событий?</h4>
              <p>Подпишитесь на нашу рассылку</p>
              <%= form_with(url: subscribers_path, :id => 'subscribe_form', locale: true, data: {type: :json}, :class => 'subscribe_form') do %>
                <span class="input-group">
                  <%= text_field(:subscriber, :email, :class => "form-control", :placeholder => "Введите ваш email", :required => true) %>
                  <span class="input-group-btn">
                    <%= submit_tag "OK", :class => "btn btn-success" %>
                  </span>
                </span>
              <% end %>
              <p class="response"></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <span class="text-muted copyrights-line">Тестовое приложение (c) <%= Time.current.year %> г.</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed-top px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <nav class="container navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" target="_blank" href="https://github.com/Seintero/ruby-test">Seintero</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarSupportedContent" style="">
      <ul class="navbar-nav mr-auto">
        <a class="nav-link waves-effect waves-light <%= current_class?('/') %> nav-item" href="/">События</a>
        <%= link_to 'Организаторы', organizers_path, class: current_class?(organizers_path) + ' nav-link waves-effect waves-light' %>
        <% if administrator_signed_in? %>
          <%= link_to admin_root_url, class: 'nav-link waves-effect waves-light' do %>
            Панель администратора
          <% end %>
          <%= link_to destroy_administrator_session_path, method: :delete, class: 'nav-link waves-effect waves-light' do %>
            <i class="fa fa-sign-out" aria-hidden="true"></i> Выйти
          <% end %>
        <% else %>
          <%= link_to new_administrator_session_path, class: 'nav-link waves-effect waves-light' do %>
            <i class="fa fa-sign-in" aria-hidden="true"></i> Войти
          <% end %>
        <% end %>
      </ul>
      <%= form_with(url: search_events_path, method: "get", local: true, remote: false, :class => 'form-inline') do %>
        <%= text_field_tag :search, params[:search], :class => "form-control mr-sm-2", :placeholder => "Поиск", :required => true %>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          <i class="fa fa-search" aria-hidden="true"></i>
        </button>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= yield(:stylesheets) %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render 'layouts/header' %>
<main role="main" class="pt-5">
  <%= yield %>
</main>
<%= render 'layouts/footer' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'false' %>
<%= javascript_include_tag 'jquery-3.5.1.min' %>
<%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js' %>
<%= yield(:javascripts) %>
<%= javascript_include_tag 'main' %>
</body>
</html>